In [1]:
!pip install numpy

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) - skipping


Load in NymPy

In [2]:
import numpy as np

The Basics

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9. , 8., 7.],[6. , 5., 4.]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#Get dimension
a.ndim

1

In [7]:
#Get shape 
a.shape

(3,)

In [8]:
#Get type 
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.nbytes

12

Acessing/changing specific elements , rows , columns, etc.

In [11]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9 , 10 , 11 , 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [row, column]

a[1,4], a[1, -2]

(12, 13)

In [14]:
#Get a pecific row 
a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a peccific column
a[: , 2]

array([ 3, 10])

In [16]:
#Getting  a little more fancy {startindex : endindex : stepsize}
a[0, 1:6:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3-d example


In [20]:
b = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# GEt specific element (work outside in)
b[0,1,1]

4

In [23]:
#replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initializing Different Types of arrays

In [25]:
# All 0s matrix 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#all 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [27]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# any other number (full_ like)
np.full_like(a, 10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [32]:
#random decimal numbers
np.random.rand(4,2)

array([[0.5788949 , 0.95952912],
       [0.54327633, 0.85805878],
       [0.82363696, 0.61175146],
       [0.77281154, 0.29891953]])

In [35]:
#random integer values
np.random.randint(7, size=(3,3))

array([[4, 4, 3],
       [6, 3, 5],
       [4, 1, 1]])

In [36]:
np.random.randint(-4,8, size = (3,3))

array([[-2, -4,  2],
       [ 1, -1,  0],
       [ 6,  7,  2]])

In [37]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Example 1:

In [39]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays 

In [40]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 10

print(a)
print(b)

[1 2 3]
[10  2  3]


Mathematics

In [43]:
a = np.array([1, 2, 3, 4,])
print(a)

[1 2 3 4]


In [44]:
 a + 2 

array([3, 4, 5, 6])

In [45]:
a -2

array([-1,  0,  1,  2])

In [47]:
a * 2

array([2, 4, 6, 8])

In [48]:
a/ 2

array([0.5, 1. , 1.5, 2. ])

In [49]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear algebra

In [51]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [54]:
# find the determinant of the matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [56]:
# vertically stacking vectores
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [58]:
# Horizontal stacking
h1 = np.ones((3,3))
h2 = np.zeros((3,3))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])